# Generated by Django 6.1 on 2026-09-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_onboarding_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworkconfig',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
