# Generated by Django 6.1 on 2026-09-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_socialnetworkconfig_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProfileSocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_network_links', to='profiles.publicprofile')),
                ('social_network_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_profile_links', to='profiles.socialnetworkinstance')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('public_profile', 'social_network_instance'), name='unique_public_profile_social_network')],
            },
        ),
    ]
